# Generated by Django 5.2.9 on 2025-12-09 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', help_text="Status da análise de IA (e.g., 'pending', 'processing', 'completed', 'failed').", max_length=50)),
                ('summary', models.TextField(blank=True, help_text='Resumo do conteúdo do documento gerado pela IA.', null=True)),
                ('missing_topics', models.JSONField(blank=True, help_text='Tópicos que podem estar faltando no documento, identificados pela IA.', null=True)),
                ('insights', models.JSONField(blank=True, help_text='Insights úteis extraídos do documento pela IA.', null=True)),
                ('model_used', models.CharField(blank=True, help_text="Modelo de IA utilizado para a análise (e.g., 'gemini', 'openai').", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(help_text='Documento ao qual esta análise de IA pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='document.document')),
            ],
        ),
    ]
