# Generated by Django 5.2.9 on 2025-12-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url_pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
