# Generated by Django 5.2.9 on 2025-12-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_url_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signed_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
