# Generated by Django 5.2.9 on 2025-12-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_document_signed_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='signed_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
